### PR TITLE
[feature] monitors map instead of a monitors list for fast lookups

### PR DESCRIPTION
**Pull request by sescobb27**
Move monitors list from being a state attribute to a Map, if a connection can have more than 1000 channels, then, there will be the same number of clients and monitors, there the advantage of having the monitors as a Map.

### CODE REVIEW

**Comment by bryanhuntesl** [comment]
Just to be aware - the default number of ETS tables per-node is capped at 1400 - https://elixirschool.com/en/lessons/specifics/ets/#overview - attempts to create more will crash - is there that much advantage in terms of speed as opposed to just using a Map and keeping it on the stack? If there were a single ETS table in use by the library it would seem to make more sense. Thoughts ?

**Comment by sescobb27** [comment]
is there a possibility to have that many connections to RabbitMQ? because i have tried that approach of having just 1 DB and had issues trying to clean it up after a crash or something like that (i tried creating the ETS table in the supervisor so the table only crashes when all the tree crashes) but if one connection process crashes all the monitors that were created in the table aren't deleted and we can't rely on the terminate callback of the connection process.

I didn't try having a map instead of an ETS

**Comment by Ayanda-D** [comment]
hmm, is it because poolboy workers most likely aren't anticipated to grow much? as much as RabbitMQ connections can grow, e.g. IoT, connections can get to thousands, 100k or millions. We can bump up ETS limits http://erlang.org/doc/man/erl.html#+e but I think maps or [dict](http://erlang.org/doc/man/dict.html) may be a bit more lightweight, and rabbit internals such as [pmon](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/pmon.erl#L37) make use of these for maintaining monitors, i think we can follow same pattern, maps should be fine

**Comment by bryanhuntesl** [comment]
> hmm, is it because poolboy workers most likely aren't anticipated to grow much? as much as RabbitMQ connections can grow, e.g. IoT, connections can get to thousands, 100k or millions. We can bump up ETS limits http://erlang.org/doc/man/erl.html#+e but I think maps or [dict](http://erlang.org/doc/man/dict.html) may be a bit more lightweight, and rabbit internals such as [pmon](https://github.com/rabbitmq/rabbitmq-common/blob/master/src/pmon.erl#L37) make use of these for maintaining monitors, i think we can follow same pattern, maps should be fine

Yes - the principle of least surprise. Take for example the case where someone uses this library and the system starts failing under heavy load - this was a common problem with Riak - which made use of a huge number of ETS tables - for example : 

http://lists.basho.com/pipermail/riak-users_lists.basho.com/2010-October/002300.html

**Comment by sescobb27** [comment]
@bryanhuntesl @Ayanda-D done

**Comment by bryanhuntesl** [comment]
ping - to try and trigger travis build

**Comment by bryanhuntesl** [comment]
+1 merge ahoy

**Comment by Ayanda-D** [comment]
looks good, & QA `mix test test/worker/rabbit_connection_test.exs` all pass 👍

**Pull request merged**
